"""
Django settings for opentask project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

from django.conf import settings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gi=1l96w+&v=%=6fnld+dx!j0=3s5e&2-6nnttbmrfq-btqo$1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_beat',
    'django_celery_results',
]

##################################################
#       Celery 配置
# 参考配置： https://www.bbsmax.com/A/x9J2YgoVz6/
# 参考动态：https://blog.ops-coffee.cn/s/h3lpkehj4-bwefrhnqsfcq
##################################################

# BROKER_URL = 'redis://:123456@localhost:6379/1' # Broker配置，使用Redis作为消息中间件
# CELERY_RESULT_BACKEND = 'redis://:123456@localhost:6379/2' # BACKEND配置，这里使用redis结果存储地址
# CELERY_ACCEPT_CONTENT = ['application/json'] #指定任务接收的内容序列化类型
# CELERY_TASK_SERIALIZER = 'json' #任务序列化方式
# CELERY_RESULT_SERIALIZER = 'json' #任务结果序列化方式
# CELERY_TASK_RESULT_EXPIRES =  60 * 60 * 24  #任务过期时间
# CELERY_MESSAGE_COMPRESSION = 'zlib' #是否压缩
# CELERY_WORKER_CONCURRENCY = 5  # celery 的启动工作数量设置
# CELERYD_CONCURRENCY =  20 # 并发数设置，最多可以有20个任务同时运行
# CELERYD_PREFETCH_MULTIPLIER = 20 #celery worker 每次去redis取任务的数量
# CELERYD_MAX_TASKS_PER_CHILD = 3 #每个worker最多执行3个任务就摧毁，避免内存泄漏
# CELERYD_FORCE_EXECV = True #可以防止死锁


# # beat配置
# # CELERY_ENABLE_UTC = False  #关闭时区
# DJANGO_CELERY_BEAT_TZ_AWARE = False
# CELERY_TIMEZONE = settings.TIME_ZONE # 使用亚洲/上海时区
# CELERY_IGNORE_RESULT = True
# CELERY_BEAT_SCHEDULER  = 'django_celery_beat.schedulers:DatabaseScheduler' # 开启定时任务数据库调度器
# CELERY_DISABLE_RATE_LIMITS = True # 禁用所有速度限制，如果网络资源有限，不建议开足马力。

##################################################


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'opentask.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'opentask.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
